### ISSUE TITLE
Cannot fetch access token from Spotify API

### ISSUE THREAD

**Issue by RudraAmin28** [thuanvoit/spotify-sdk-tutorial#12]
I am having issues with accessing the access token using this code. I used the same code as the example in this github and changed the redirecturi and the client id in my code. Then, I called getToken(), getCode(), and onGetUserProfileClicked() in the onCreate method of MainActivity.java. However, once I open the file, I get a Toast with the message "You need to get an access token first!" I am not sure why I can get the access token even though I have double checked the redirectURI in my app files and the Spotify Developer Dashboard. I have also checked the Client ID, and tried the troubleshooting steps at the bottom of this GitHub, but it did not change anything. 

[supportingfiles.zip](https://github.com/CS2340-SP24/spotify-sdk-tutorial/files/14767835/supportingfiles.zip)

<img width="1416" alt="Screenshot 2024-03-27 at 12 37 34 AM" src="https://github.com/CS2340-SP24/spotify-sdk-tutorial/assets/100248438/f24da245-6f1e-47f4-b66d-da6b3eeadc85">

System OS: MacOS Sonoma 14.4.1

Android Studio version: Android Studio Hedgehog

**Comment by a-stickan** [comment]
@RudraAmin28 Please update your post [with all the information we requested in the issue template.](https://github.com/thuanvoit/spotify-sdk-tutorial/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by thuanvoit** [comment]
Please use the template and send us the necessary information such as schemeName, redirectURL, etc.

**Comment by RudraAmin28** [comment]
I have updated the issue with the information requested in the template. Thank you.

**Comment by thuanvoit** [comment]
You said that "I called getToken(), getCode(), and onGetUserProfileClicked() in the onCreate method of MainActivity.java"

1. getToken() and getCode() will require login through a browser and it will return back to your app after login on browser.
2. It would take sometimes (since it is async) to get the code/token.
3. Do all three immediately would run the onGetUserProfileClicked() prior the code/token exists.

I suggest to only allow onGetUserProfileClicked() once the token exists.

This is why we separate buttons on the tutorial.
